import { MigrationInterface, QueryRunner } from 'typeorm';

const countries = [
  ['0X-9KZ4-bn12', 'Afghanistan', 'South Asia'],
  ['1u72_4u418a-', 'Åland Islands', 'Europe'],
  ['CLnsv_5-7_0B', 'Albania', 'Europe'],
  ['0e2TeQXI99OD', 'Algeria', 'Middle East & North Africa'],
  ['K_CEV_lX8c3f', 'American Samoa', 'Oceania'],
  ['Xd-fp_qBZCcu', 'Andorra', 'Europe'],
  ['lBt6Jv5FP5am', 'Angola', 'Sub-Saharan Africa'],
  ['9XWCY7NO923I', 'Anguilla', 'Latin America & Caribbean'],
  ['4KojGR2DsULL', 'Antigua and Barbuda', 'Latin America & Caribbean'],
  ['pc6wtQ314RX4', 'Argentina', 'Latin America & Caribbean'],
  ['_44Q35wd871g', 'Armenia', 'Middle East & North Africa'],
  ['PX74O-3_G_jZ', 'Aruba', 'Latin America & Caribbean'],
  ['-yD9f8d5oX-K', 'Australia', 'Oceania'],
  ['rtu7h7v1527-', 'Austria', 'Europe'],
  ['0e0pG-1j_yI8', 'Azerbaijan', 'Middle East & North Africa'],
  ['7Mbl4Jm4oAnX', 'Bahamas', 'Latin America & Caribbean'],
  ['84ApRs951_gF', 'Bahrain', 'Middle East & North Africa'],
  ['q20u-92-04wr', 'Bangladesh', 'South Asia'],
  ['046SwIQ3C3UR', 'Barbados', 'Latin America & Caribbean'],
  ['Ho3863MQ_-0O', 'Belarus', 'Europe'],
  ['510Bk0z10yO-', 'Belgium', 'Europe'],
  ['xvN-_6m8Nk2C', 'Belize', 'Latin America & Caribbean'],
  ['i2625o5q54X2', 'Benin', 'Sub-Saharan Africa'],
  ['27-hAjd83531', 'Bermuda', 'North America'],
  ['aC3_w-gJN06M', 'Bhutan', 'South Asia'],
  ['u_VCLlgFfy1Q', 'Bolivia', 'Latin America & Caribbean'],
  ['OJ8Y05JC04tT', 'Caribbean Netherlands', 'Latin America & Caribbean'],
  ['Umqv0_5YN-6-', 'Bosnia and Herzegovina', 'Europe'],
  ['U1-63_h1aW_x', 'Botswana', 'Sub-Saharan Africa'],
  ['-d-P7Ual_oM_', 'Bouvet Island', 'Latin America & Caribbean'],
  ['feQ75-C6I459', 'Brazil', 'Latin America & Caribbean'],
  ['x2yzq5VEv-wt', 'British Indian Ocean Territory', 'Sub-Saharan Africa'],
  ['LGW-h9nS63zA', 'British Virgin Islands', 'Latin America & Caribbean'],
  ['h4zG1sUEens2', 'Brunei', 'Southeast Asia'],
  ['m-W-e674306y', 'Bulgaria', 'Europe'],
  ['y2a7-hmWP2eR', 'Burkina Faso', 'Sub-Saharan Africa'],
  ['_3v7_3_g4351', 'Burundi', 'Sub-Saharan Africa'],
  ['g5Hwzbf_PcQ8', 'Cabo Verde', 'Sub-Saharan Africa'],
  ['aa2_E0ov00Zy', 'Cambodia', 'Southeast Asia'],
  ['6-1Z5535lffX', 'Cameroon', 'Sub-Saharan Africa'],
  ['Y_0z8rAlmnWf', 'Canada', 'North America'],
  ['0rjLZvwVdwr2', 'Cayman Islands', 'Latin America & Caribbean'],
  ['_L6tzRJQHAun', 'Central African Republic', 'Sub-Saharan Africa'],
  ['_6NJ6ppYJHro', 'Chad', 'Sub-Saharan Africa'],
  ['XO_26okvB2hF', 'Chile', 'Latin America & Caribbean'],
  ['jIYfP-_3Z1_w', 'China', 'East Asia'],
  ['TAYdZYlm326X', 'Hong Kong', 'East Asia'],
  ['3c_n77JMU3m6', 'Macau', 'East Asia'],
  ['-4I6_0FZ_6VO', 'Christmas Island', 'Oceania'],
  ['d993O-NXZ1Pn', 'Cocos (Keeling) Islands', 'Oceania'],
  ['0YWq_Z26E7_t', 'Colombia', 'Latin America & Caribbean'],
  ['8e2YvdB70gZ-', 'Comoros', 'Sub-Saharan Africa'],
  ['U3dFgG9ge7k6', 'Congo', 'Sub-Saharan Africa'],
  ['UaWyMJZVw-_e', 'Cook Islands', 'Oceania'],
  ['IKU164838ySC', 'Costa Rica', 'Latin America & Caribbean'],
  ['0poqAD5OdBN_', 'Côte d’Ivoire', 'Sub-Saharan Africa'],
  ['T-8C0--JLy1i', 'Croatia', 'Europe'],
  ['_9rd_8z4azBH', 'Cuba', 'Latin America & Caribbean'],
  ['S09_n_6GKc6a', 'Curaçao', 'Latin America & Caribbean'],
  ['-wpzN_q7ax58', 'Cyprus', 'Middle East & North Africa'],
  ['sFhLviA8_0RR', 'Czechia', 'Europe'],
  ['g-BfV7E0PgXs', 'North Korea', 'East Asia'],
  ['q1sxU_gbqh5-', 'Democratic Republic of the Congo', 'Sub-Saharan Africa'],
  ['q-ESVaO9VH8c', 'Denmark', 'Europe'],
  ['JX_1J3wq6DZm', 'Djibouti', 'Sub-Saharan Africa'],
  ['-3x5a8tl77-j', 'Dominica', 'Latin America & Caribbean'],
  ['r_7rPxBVwW5G', 'Dominican Republic', 'Latin America & Caribbean'],
  ['024B-K7GJQL4', 'Ecuador', 'Latin America & Caribbean'],
  ['-Xl1V56J365u', 'Egypt', 'Middle East & North Africa'],
  ['qfYrlwHg57O0', 'El Salvador', 'Latin America & Caribbean'],
  ['V_-iaT2YL13_', 'Equatorial Guinea', 'Sub-Saharan Africa'],
  ['X_ump-II_2Bo', 'Eritrea', 'Sub-Saharan Africa'],
  ['t_46_Im_Uyns', 'Estonia', 'Europe'],
  ['K5bseJON0D-r', 'Eswatini', 'Sub-Saharan Africa'],
  ['2y-ALXSx_E2-', 'Ethiopia', 'Sub-Saharan Africa'],
  ['0M_3mk5ibaV4', 'Falkland Islands', 'Latin America & Caribbean'],
  ['XirjD-x-DpE3', 'Faroe Islands', 'Europe'],
  ['Heelam67UkUr', 'Fiji', 'Oceania'],
  ['I7px3-M4Ru3X', 'Finland', 'Europe'],
  ['knW_D-T-ZAkD', 'France', 'Europe'],
  ['V7-3K13-ai24', 'French Guiana', 'Latin America & Caribbean'],
  ['22-SpMT-i64T', 'French Polynesia', 'Oceania'],
  ['59z6ZJp4yn45', 'French Southern Territories', 'Sub-Saharan Africa'],
  ['VrMZ-f0xgLwP', 'Gabon', 'Sub-Saharan Africa'],
  ['tmu61ZMaXDv3', 'Gambia', 'Sub-Saharan Africa'],
  ['cO34-SVAb14q', 'Georgia', 'Middle East & North Africa'],
  ['62YL2ZM3Ygb-', 'Germany', 'Europe'],
  ['yMvH16cvsYa0', 'Ghana', 'Sub-Saharan Africa'],
  ['QZWBI1W3UZ2g', 'Gibraltar', 'Europe'],
  ['22a908iJOP1F', 'Greece', 'Europe'],
  ['u2bVa-SpE70b', 'Greenland', 'North America'],
  ['M31LC4T---7w', 'Grenada', 'Latin America & Caribbean'],
  ['Zz8lX0gQXv35', 'Guadeloupe', 'Latin America & Caribbean'],
  ['90-w46-41gJ7', 'Guam', 'Oceania'],
  ['mUxNhcplWJ-2', 'Guatemala', 'Latin America & Caribbean'],
  ['vxdOfSx-0-r1', 'Guernsey', 'Europe'],
  ['1fRbvU2C_58N', 'Guinea', 'Sub-Saharan Africa'],
  ['ld-6548GfoB_', 'Guinea-Bissau', 'Sub-Saharan Africa'],
  ['cYY30JTo_eYh', 'Guyana', 'Latin America & Caribbean'],
  ['H6SLe_Q8ka-3', 'Haiti', 'Latin America & Caribbean'],
  ['ynZd_A1R2O2U', 'Heard Island and McDonald Islands', 'Oceania'],
  ['401Tx_sW8Zht', 'Vatican City', 'Europe'],
  ['6R2wn23YWMkg', 'Honduras', 'Latin America & Caribbean'],
  ['0a_27-_377T3', 'Hungary', 'Europe'],
  ['2rz_Bnx_e4_t', 'Iceland', 'Europe'],
  ['9vTaqoB44lSv', 'India', 'South Asia'],
  ['_04H4Wl9ffFu', 'Indonesia', 'Southeast Asia'],
  ['27i3v-5A5bNU', 'Iran', 'South Asia'],
  ['63LrU-W_z3IL', 'Iraq', 'Middle East & North Africa'],
  ['kM6AY_5K3_6_', 'Ireland', 'Europe'],
  ['LD2QJm8qq31G', 'Isle of Man', 'Europe'],
  ['tLVy_9WxGzDV', 'Israel', 'Middle East & North Africa'],
  ['401SL244lrom', 'Italy', 'Europe'],
  ['l2yNci8V7h8P', 'Jamaica', 'Latin America & Caribbean'],
  ['G8a1N10Z2Hx_', 'Japan', 'East Asia'],
  ['RLSOLQQI2D4Q', 'Jersey', 'Europe'],
  ['d1RU4--Vo6N5', 'Jordan', 'Middle East & North Africa'],
  ['1c3whUjR69J_', 'Kazakhstan', 'Middle East & North Africa'],
  ['Os5Mujcd3O3d', 'Kenya', 'Sub-Saharan Africa'],
  ['TASTIjRDkp30', 'Kiribati', 'Oceania'],
  ['Z9Mf5eD0t74y', 'Kuwait', 'Middle East & North Africa'],
  ['P4Pz6_g1-Jw_', 'Kyrgyzstan', 'Middle East & North Africa'],
  ['QHZt5oo2d0v9', 'Laos', 'Southeast Asia'],
  ['5xl909ScNK54', 'Latvia', 'Europe'],
  ['b52eu04_eeDU', 'Lebanon', 'Middle East & North Africa'],
  ['Q5q7mB8tLHHf', 'Lesotho', 'Sub-Saharan Africa'],
  ['3HZy2-1SGHi-', 'Liberia', 'Sub-Saharan Africa'],
  ['6M31kJ_kb9K5', 'Libya', 'Middle East & North Africa'],
  ['5TU1n1Bo-4-7', 'Liechtenstein', 'Europe'],
  ['44idW0NDnC9U', 'Lithuania', 'Europe'],
  ['rO6lodr-_Mq-', 'Luxembourg', 'Europe'],
  ['28yF9S333Z-y', 'Madagascar', 'Sub-Saharan Africa'],
  ['m2wJ89y_4_vR', 'Malawi', 'Sub-Saharan Africa'],
  ['MehLx7-Ln11j', 'Malaysia', 'Southeast Asia'],
  ['k0-iS9uQM4A9', 'Maldives', 'South Asia'],
  ['AO45f62a23qr', 'Mali', 'Sub-Saharan Africa'],
  ['4-bI2VDa01dr', 'Malta', 'Europe'],
  ['u4I0K4x6-0R3', 'Marshall Islands', 'Oceania'],
  ['QP_23-s2zU_c', 'Martinique', 'Latin America & Caribbean'],
  ['8741P67_cVz3', 'Mauritania', 'Sub-Saharan Africa'],
  ['v_8d0D1Sb-17', 'Mauritius', 'Sub-Saharan Africa'],
  ['5-_9_rxNwPq-', 'Mayotte', 'Sub-Saharan Africa'],
  ['nlQYp_VhMK54', 'Mexico', 'Latin America & Caribbean'],
  ['9i20zX7274uy', 'Micronesia', 'Oceania'],
  ['kl8B0CLz63Db', 'Monaco', 'Europe'],
  ['P-qT_hh4j8J2', 'Mongolia', 'East Asia'],
  ['j197brBv7Rzp', 'Montenegro', 'Europe'],
  ['bq6G_oLsU8S2', 'Montserrat', 'Latin America & Caribbean'],
  ['_8S9--5H9sKp', 'Morocco', 'Middle East & North Africa'],
  ['3-E5_fY228kZ', 'Mozambique', 'Sub-Saharan Africa'],
  ['mN_ng82v6C4E', 'Myanmar', 'Southeast Asia'],
  ['9_3qhUbyXRC1', 'Namibia', 'Sub-Saharan Africa'],
  ['q97BV42_GfO9', 'Nauru', 'Oceania'],
  ['93C01z_waasK', 'Nepal', 'South Asia'],
  ['VSz1rAAY9eB6', 'Netherlands', 'Europe'],
  ['rwgKe0Su2GNF', 'New Caledonia', 'Oceania'],
  ['9oMDt61Vu58B', 'New Zealand', 'Oceania'],
  ['XElEu94n1r96', 'Nicaragua', 'Latin America & Caribbean'],
  ['46XzA1o9BHph', 'Niger', 'Sub-Saharan Africa'],
  ['3n112r19K_fy', 'Nigeria', 'Sub-Saharan Africa'],
  ['B-_u-fxkz-_g', 'Niue', 'Oceania'],
  ['90X6iWQ71m4i', 'Norfolk Island', 'Oceania'],
  ['bI_q3zwW8q34', 'North Macedonia', 'Europe'],
  ['OWF_49l376VQ', 'Northern Mariana Islands', 'Oceania'],
  ['1F9970w-g8O2', 'Norway', 'Europe'],
  ['7D4_cKl31R__', 'Oman', 'Middle East & North Africa'],
  ['VBWn7y5fXv_E', 'Pakistan', 'South Asia'],
  ['31-I169S8U2v', 'Palau', 'Oceania'],
  ['LM0ppio2LR5R', 'Panama', 'Latin America & Caribbean'],
  ['UWNO3y_iFnTB', 'Papua New Guinea', 'Oceania'],
  ['4E90yetO3JyC', 'Paraguay', 'Latin America & Caribbean'],
  ['lF9rqO4zJov_', 'Peru', 'Latin America & Caribbean'],
  ['Z-YdwMsL56FB', 'Philippines', 'Southeast Asia'],
  ['EgH8r2-1LjuM', 'Pitcairn', 'Oceania'],
  ['5qy_jXyHGgpS', 'Poland', 'Europe'],
  ['0JR5fW580xW_', 'Portugal', 'Europe'],
  ['-w6p1B93Ut8-', 'Puerto Rico', 'Latin America & Caribbean'],
  ['DAfnepo04_V4', 'Qatar', 'Middle East & North Africa'],
  ['2f61okIS92le', 'South Korea', 'East Asia'],
  ['0WQMRM-19ks9', 'Moldova', 'Europe'],
  ['TL_Fz0J6YGe8', 'Réunion', 'Sub-Saharan Africa'],
  ['g649_6N91V9b', 'Romania', 'Europe'],
  ['k-iBj_OZLBvu', 'Russia', 'Europe'],
  ['WxHP9i0Jd_5l', 'Rwanda', 'Sub-Saharan Africa'],
  ['B_7ay8-qjFU_', 'Saint Barthélemy', 'Latin America & Caribbean'],
  ['6lqu-06z5_Li', 'Saint Helena', 'Sub-Saharan Africa'],
  ['uQ6iT3uGWp_V', 'Saint Kitts and Nevis', 'Latin America & Caribbean'],
  ['o-i1_pBYQgH4', 'Saint Lucia', 'Latin America & Caribbean'],
  ['acv8j4-07-N-', 'Saint Martin', 'Latin America & Caribbean'],
  ['Q6B-57S-mrMm', 'Saint Pierre and Miquelon', 'North America'],
  [
    '-8skEaXbWhX9',
    'Saint Vincent and the Grenadines',
    'Latin America & Caribbean',
  ],
  ['402NcWzEOB6o', 'Samoa', 'Oceania'],
  ['4_3aH8F-DCRQ', 'San Marino', 'Europe'],
  ['F9eM2d0mFTK0', 'Sao Tome and Principe', 'Sub-Saharan Africa'],
  ['X60m0u99AMIj', 'Sark', 'Europe'],
  ['-l0269Vbl0-n', 'Saudi Arabia', 'Middle East & North Africa'],
  ['7UtfGHP_osDu', 'Senegal', 'Sub-Saharan Africa'],
  ['o1p1KMd1oYVf', 'Serbia', 'Europe'],
  ['9nT5M94k64V-', 'Seychelles', 'Sub-Saharan Africa'],
  ['O0-iD_fF_0et', 'Sierra Leone', 'Sub-Saharan Africa'],
  ['_pmSg75U99s2', 'Singapore', 'Southeast Asia'],
  ['2-v0D62Re_27', 'Sint Maarten', 'Latin America & Caribbean'],
  ['F2F042RNj8k0', 'Slovakia', 'Europe'],
  ['q-Q3l7PRF28X', 'Slovenia', 'Europe'],
  ['0F59BL0_0itr', 'Solomon Islands', 'Oceania'],
  ['lcaxrJrk0g0d', 'Somalia', 'Sub-Saharan Africa'],
  ['9m_7p86L7Q32', 'South Africa', 'Sub-Saharan Africa'],
  [
    'dg0N39qe2MZ8',
    'South Georgia and the South Sandwich Islands',
    'Latin America & Caribbean',
  ],
  ['IRGoM-dIOk84', 'South Sudan', 'Sub-Saharan Africa'],
  ['_83Fr_2GAI4f', 'Spain', 'Europe'],
  ['-F_mbvFnjb8X', 'Sri Lanka', 'South Asia'],
  ['F2Tvw159K-va', 'Palestine', 'Middle East & North Africa'],
  ['55Ddqftbyr-9', 'Sudan', 'Middle East & North Africa'],
  ['4wu8_Qu9fsXm', 'Suriname', 'Latin America & Caribbean'],
  ['8P3b3aDA0Ml2', 'Svalbard and Jan Mayen', 'Europe'],
  ['6Qt8J1255Huy', 'Sweden', 'Europe'],
  ['v-_1o_YMO__o', 'Switzerland', 'Europe'],
  ['gr4zk3V2L4__', 'Syria', 'Middle East & North Africa'],
  ['_m35BTHbL_3R', 'Tajikistan', 'Middle East & North Africa'],
  ['9yB7nJ4oTszr', 'Thailand', 'Southeast Asia'],
  ['2-8jH4_hp8PO', 'Timor-Leste', 'Southeast Asia'],
  ['H5-8M4CSL4xL', 'Togo', 'Sub-Saharan Africa'],
  ['dOe-r7--L_U9', 'Tokelau', 'Oceania'],
  ['N8WfyRGEg0e0', 'Tonga', 'Oceania'],
  ['dgLZvIY2_te-', 'Trinidad and Tobago', 'Latin America & Caribbean'],
  ['KZi_Si8-wf_1', 'Tunisia', 'Middle East & North Africa'],
  ['ZahZnU90B-Ux', 'Turkey', 'Middle East & North Africa'],
  ['tX-ht5pks1ei', 'Turkmenistan', 'Middle East & North Africa'],
  ['5U10kAB96zfd', 'Turks and Caicos Islands', 'Latin America & Caribbean'],
  ['90oGq36ko08W', 'Tuvalu', 'Oceania'],
  ['l80G159M8G_q', 'Uganda', 'Sub-Saharan Africa'],
  ['_3568F8Rn8_6', 'Ukraine', 'Europe'],
  ['61g-7u19V28N', 'United Arab Emirates', 'Middle East & North Africa'],
  ['_zWAr5P2s0YK', 'United Kingdom', 'Europe'],
  ['69h-yRD1o1b2', 'United Republic of Tanzania', 'Sub-Saharan Africa'],
  ['aru89234SWEN', 'United States Minor Outlying Islands', 'Oceania'],
  ['zaX2_k_7t9b-', 'United States', 'North America'],
  ['3_3_2zc3y_WE', 'United States Virgin Islands', 'Latin America & Caribbean'],
  ['86oP91BTV_LT', 'Uruguay', 'Latin America & Caribbean'],
  ['5lt9Z1xk-bp4', 'Uzbekistan', 'Middle East & North Africa'],
  ['Yjz098oxNhA-', 'Vanuatu', 'Oceania'],
  ['G_8S3TKV9rLv', 'Venezuela', 'Latin America & Caribbean'],
  ['j2L6Y9I8Vjt1', 'Vietnam', 'Southeast Asia'],
  ['_WE44z5y_h--', 'Wallis and Futuna', 'Oceania'],
  ['QZ8pS0C6VbWI', 'Western Sahara', 'Middle East & North Africa'],
  ['XysRTNfCWNLk', 'Yemen', 'Middle East & North Africa'],
  ['tFiH58C8Brcj', 'Zambia', 'Sub-Saharan Africa'],
  ['FY4S8CTgSlRH', 'Zimbabwe', 'Sub-Saharan Africa'],
];

export class CreateCountryTable1768231490469 implements MigrationInterface {
  name = 'CreateCountryTable1768231490469';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "country" ("id" character varying NOT NULL, "name" character varying NOT NULL, "region" character varying NOT NULL, CONSTRAINT "PK_bf6e37c231c4f4ea56dcd887269" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "artist" ADD "countryId" character varying`,
    );
    await queryRunner.query(
      `ALTER TABLE "artist" ADD CONSTRAINT "FK_28744e1467376c11a7b071f404f" FOREIGN KEY ("countryId") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `INSERT INTO "country" ("id", "name", "region") VALUES ${countries.map(
        (country) => `('${country[0]}', '${country[1]}', '${country[2]}')`,
      )}`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "artist" DROP CONSTRAINT "FK_28744e1467376c11a7b071f404f"`,
    );
    await queryRunner.query(`ALTER TABLE "artist" DROP COLUMN "countryId"`);
    await queryRunner.query(`DROP TABLE "country"`);
  }
}
