export const TOP_RELEASES_OAT_MAX_RATINGS_COUNT = null;
export const TOP_RELEASES_OAT_MIN_RATINGS_COUNT = 35;
export const TOP_RELEASES_OTY_MAX_RATINGS_COUNT = null;
export const TOP_RELEASES_OTY_MIN_RATINGS_COUNT = 30;
